### PR TITLE
Add CircleCI to repository

### PR DESCRIPTION
**Pull request by robskillington**

### CODE REVIEW

**Comment by robskillington** [comment]
Hm still doesn't seem to be added for the project @RichiH or @SuperQ could you help out?

Think it needs to get added as a project from this page here (I get just "No matching repos for organization OpenObservability" from this page):
https://circleci.com/add-projects/gh/OpenObservability

**Comment by SuperQ** [comment]
I've enabled CircleCI, but you need to push a change to the config to trigger a run.

**Comment by robskillington** [comment]
@SuperQ I took forever to to attempt triggering a run, just tried now, not sure why CircleCI not running however. Is there something I'm missing in `.circleci/config.yml`?

**Comment by Jamim** [comment]
Hi there,
Shouldn't this PR be closed?

**Comment by SuperQ** [comment]
Yes, this looks obsolete.

**Pull request closed without merging**
