### PR TITLE
Add remaining OpenMetrics logos

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds the logos contained in [this ZIP file](https://github.com/RichiH/OpenMetrics/files/1734530/openmetrics.zip) (don't click or else it will download). We don't have uses for all of these yet but I figure they might as well be in the repo.

### CODE REVIEW

**Comment by RichiH** [comment]
What is openrgb.eps? I can't open this for some reason.

Can you rename to `open.*` to `logo_with_text.*`, please?

**Comment by lucperkins** [comment]
@RichiH I'm not actually sure what the `*.eps` files are. I'm thinking maybe we can keep them for now and leave open the option of removing them later.

**Comment by RichiH** [comment]
GIMP managed to import them, but I don't know what, if anything, changed while importing.

`foorgb` -> `foo-rgb` and `open` -> `logo-with-text` and we are good to merge.

FTR: The .ai seems to be the source format. @caniszczyk can you check if the artist has any more files we should add here? Especially SVG would be useful.

**Comment by RichiH** [comment]
PS: Intention is to also have all raw formats in case we ever need to make changes. I don't really speak GFX so no idea if .ai is enough.

**Comment by lucperkins** [comment]
@RichiH Okay, that should do it. I can open a separate PR when we know more about SVGs and such.

**Pull request merged**
